repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8.git
    rev: 7.1.0
    hooks:
      - id: flake8
        args: ['--max-line-length=100']
  - repo: https://github.com/pylint-dev/pylint.git
    rev: v3.2.6
    hooks:
      - id: pylint
        language: system
  - repo: https://github.com/PyCQA/isort.git
    rev: 5.13.2
    hooks:
      - id: isort
