version: '3.4'
services:
  db:
    image: postgres:11-alpine
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: hello
      POSTGRES_DB: tradesdb
      POSTGRES_USER: deq
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U deq -d tradesdb"]
      interval: 5s
      timeout: 5s

  web:
    build: .
    container_name: python_app
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      DATABASE_URL: "postgresql://deq:hello@db:5432/tradesdb"
    ports:
      - "5000:5000"

volumes:
  postgres_data:
